# Site settings
title: Swift Hacks
description: > # this means to ignore newlines until "baseurl:"
  Site to share Swift develop hints
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.swifthacks.net" # the base hostname & protocol for your site
github_username:  skeleton9

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]

# markdown: kramdown
